version: "2.4"

services:
  trtis-server-container-gpu:
    extends:
      file: docker-compose.yml
      service: trtis-server-container
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    container_name: trtis-server-container-gpu
  trtis-custom-backend-build-container-gpu:
    extends:
      file: docker-compose.yml
      service: trtis-custom-backend-build-container
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    build: 
      context: ./docker
      dockerfile: ./custom_backend/Dockerfile.gpu
    container_name: trtis-custom-backend-build-container-gpu
  data-uploader-container:
    extends:
      file: docker-compose.yml
      service: data-uploader-container
  trtis-client-container:
    extends:
      file: docker-compose.yml
      service: trtis-client-container
